(G-CODE GENERATED BY FLATCAM v8.994 - www.flatcam.org - Version Date: 2020/11/7)

(Name: Drill_PTH_Through.DRL_edit_0_5_cnc)
(Type: G-code from Geometry)
(Units: MM)

(Created on Wednesday, 08 June 2022 at 17:32)

(This preprocessor is used with a motion controller loaded with GRBL firmware.)
(It is configured to be compatible with almost any version of GRBL firmware.)


(TOOLS DIAMETER: )
(Tool: 1 -> Dia: 0.5)

(FEEDRATE Z: )
(Tool: 1 -> Feedrate: 60.0)

(FEEDRATE RAPIDS: )
(Tool: 1 -> Feedrate Rapids: 1500)

(Z_CUT: )
(Tool: 1 -> Z_Cut: -1.8)

(Tools Offset: )
(Tool: 1 -> Offset Z: 0.0)

(Z_MOVE: )
(Tool: 1 -> Z_Move: 2)

(Z Toolchange: 20.0 mm)
(X,Y Toolchange: 0.0000, 0.0000 mm)
(Z Start: None mm)
(Z End: 0.5 mm)
(X,Y End: None mm)
(Steps per circle: 64)
(Steps per circle: 64)
(Preprocessor Excellon: grbl_11)

(X range:   52.6770 ...   53.1770  mm)
(Y range:  -16.7910 ...  -16.2910  mm)

(Spindle Speed: 100 RPM)
G21
G90
G17
G94


G01 F60.00

M5             
G00 Z20.0000
G00 X0.0000 Y0.0000                
T1
M6
(MSG, Change to Tool Dia = 0.5000 ||| Total drills for tool T1 = 1)
M0
G00 Z20.0000

G01 F60.00
M03 S100
G4 P1
G00 X52.9270 Y-16.5410
G01 Z-1.8000
G01 Z0
G00 Z2.0000
M05
G00 Z0.50


